version: '3'

services:
  web:
    image: base-app:v8
    depends_on: 
      - postgres
    working_dir: /app
    ports:
      - "3000:3000"
  postgres:
    image: database:v1
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Manhtung1@"
    ports:
      - "5432:5432"
